# load
command: write
command_options:
output_format: cassandra-stress.{{command}}.{{load_name}}.{{ansible_date_time.date}}
output_file: "{{output_format}}"
stress_options:
populate: 1000000

rate: "threads=250"

profile_dir: /tmp/cassandra-stress-profiles/
