---
- name: download collectd_exporter.tar.gz
  get_url: url=https://github.com/prometheus/collectd_exporter/releases/download/{{collectd_exporter_ver}}/collectd_exporter-{{collectd_exporter_ver}}.linux-amd64.tar.gz dest={{install_dir}}/collectd_exporter.tar.gz

- name: extract collectd_exporter.tar.gz
  unarchive: src={{install_dir}}/collectd_exporter.tar.gz dest={{install_dir}}/ copy=no

- command: '{{install_dir}}/collectd_exporter -collectd.listen-address="0.0.0.0:65534"'
  async: 604800
  poll: 0

- name: upload scylla collectd config
  template: src=scylla.conf dest=/etc/collectd.d/scylla.conf owner=root group=root

- name: restart collectd service
  service: name=collectd state=restarted
