---
- name: start collectd-exporter container
  docker:
    docker_api_version: 1.21
    name: collectd-exporter
    image: prom/collectd-exporter
    ports:
    - "9103:9103"
    state: started

- name: upload scylla collectd config
  template: src=scylla.conf dest=/etc/collectd.d/scylla.conf owner=root group=root

- name: restart collectd service
  service: name=collectd state=restarted
