- service: name=scylla-server enabled=yes state=stopped
- debug: msg="clean {{data_dir}}"
- file: path={{data_dir}}/data state=absent
- file: path={{data_dir}}/commitlog state=absent
- file: path={{data_dir}}/data state=directory owner=scylla group=scylla
- file: path={{data_dir}}/commitlog state=directory owner=scylla group=scylla
