---
- name: start scylla service
  action: service name=scylla-server enabled=yes state=restarted
  sudo: yes

## scylla-jmx goes down if scylla-server goes down, but not the other way around.
## See issue https://github.com/scylladb/scylla/issues/504
- name: wait for scylla service to complete its init procedures
  wait_for: host={{ansible_all_ipv4_addresses[0]}} port=9042 timeout=600

- name: start scylla-jmx service
  action: service name=scylla-jmx enabled=yes state=restarted
  sudo: yes

- name: Gather facts
  action: ec2_facts

- set_fact:
    id: "{{ansible_ec2_instance_id}}"
    region: "{{ ansible_ec2_placement_availability_zone | regex_replace('(.*[1-9])(.)', '\\\\1' ) }}"
  when: ansible_ec2_instance_id is defined

- name: Tag instance as none stopped
  local_action: ec2_tag resource={{id}} state=present region={{region}}
  when: ansible_ec2_instance_id is defined
  args:
    tags:
      stopped: "false"

- name: Give everyone a minute or two
  pause: seconds={{wait_after_adding_server}}
