---
- service: name=scylla-server enabled=yes state=stopped
  sudo: yes
- name: Gather facts
  action: ec2_facts
- set_fact:
    id: "{{ansible_ec2_instance_id}}"
    region: "{{ ansible_ec2_placement_availability_zone | regex_replace('(.*[1-9])(.)', '\\\\1' ) }}"
  when: ansible_ec2_instance_id is defined

- name: Tag instance as Stopped
  local_action: ec2_tag resource={{id}} state=present region={{region}}
  when: ansible_ec2_instance_id is defined
  args:
    tags:
      stopped: "true"

- { include: clean.yaml, sudo: yes , when: clean_data == 'true' }
