---
collectd_url: http://collectd.org/files/
collectd_version: collectd-5.4.1

java_home: /usr/lib/jvm/java-7-oracle

internal_ip: "{{ansible_all_ipv4_addresses[0]}}"

## for init.d-template.j2
daemon_user: "${RUNAS:-root}"
daemon: /usr/sbin/collectd
pidfile: /var/run/collectd.pid
daemon_opts: "-P /var/run/collectd.pid -C /etc/collectd/collectd.conf"
service_name: collectd
pidfile_opts:


