---
- name: Clean Data Cassandra
  hosts: "Cassandra:!Stopped"
  user: "{{cassandra_login}}"
  tasks:
    - include_vars: roles/cassandra-config/vars/main.yaml
      when: server == "Cassandra" and clean_data | bool
    - { include: roles/cassandra-config/tasks/clean.yaml, become: true , when: server == "Cassandra" and clean_data | bool }

- name: Restart Cassandra Service - one by one
  hosts: "Cassandra:!Stopped"
  user: "{{cassandra_login}}"
  tasks:
    - { include: roles/cassandra-config/tasks/start.yaml, when: server == "Cassandra" and  clean_data | bool }

- name: Clean Data Scylla
  hosts: "Scylla:!Stopped"
  user: "{{scylla_login}}"
  tasks:
    - include_vars: roles/scylla-config/vars/main.yaml
      when: server == "Scylla" and clean_data | bool
    - { include: roles/scylla-config/tasks/clean.yaml, become: true , when: server == "Scylla" and clean_data | bool }

- name: Restart Scylla Service - one by one
  hosts: "Scylla:!Stopped"
  user: "{{scylla_login}}"
  tasks:
    - { include: roles/scylla-config/tasks/start.yaml, when: server == "Scylla" and clean_data | bool }

