- name: Prepare Cassandra nodes
  hosts: NewDB
  user: "{{cassandra_login}}"
  tasks:
    - name: wait for cassandra service to complete its init procedures
      wait_for: host={{ansible_all_ipv4_addresses[0]}} port=9042 timeout=600

- name: Prepare Cassandra nodes
  hosts: NewDB
  user: "{{cassandra_login}}"
  roles:
    - { role: cassandra-install, become: true, when: not use_db_ami|bool}
    - { role: cassandra-config, become: true, when: ec2_multiregion|bool or add_node|bool or not use_db_ami|bool}
    - { role: collectd-client, become: true, tag: "stress", when: collectd_server is defined}

- name: Run Cassandra nodes
  hosts: NewDB
  user: "{{cassandra_login}}"
  tasks:
    - include: roles/cassandra-config/tasks/start.yaml
      when: not stopped|bool and (ec2_multiregion|bool or add_node|bool or collectd_server is defined)
