- name: Prepare Cassandra nodes
  hosts: NewDB
  user: "{{cassandra_login}}"
  roles:
    - { role: cassandra-install, sudo: yes, when: not use_db_ami|bool}
    - { role: cassandra-config, sudo: yes, when: ec2_multiregion|bool or not use_db_ami|bool}
    - { role: collectd-client, sudo: yes, tag: "stress", when: not use_db_ami|bool}

- name: Run Cassandra nodes
  hosts: NewDB
  serial: 1
  user: "{{cassandra_login}}"
  tasks:
    - include: roles/cassandra-config/tasks/start.yaml
      when: ec2_multiregion|bool or not stopped|bool
