---
- name: Provision Cassandra load generators EC2
  hosts: localhost
  connection: local
  vars:
  tasks:

    - name: Launch instances
      local_action:
        module: ec2
        region: "{{item.value.region_name}}"
        keypair: "{{item.value.key_name}}"
        group: "{{item.value.security_group}}"
        vpc_subnet_id: "{{item.value.vpc_subnet_id}}"
        assign_public_ip: yes
        instance_type: "{{instance_type}}"
        image: "{{item.value.fedora_ami}}"
        count: "{{ load_nodes}}"
        instance_tags:
          Name: "CassandraLoadgen"
          user: "{{setup_name}}"
        wait: yes
      register: ec2_load
      with_dict: use_regions

    - name: Wait for SSH to come up
      wait_for: host={{item.1.public_ip}} port=22 delay=60 timeout=320 state=started
      with_subelements:
        - ec2_load.results
        - instances

    - name: Add instances to host group
      local_action: add_host name={{item.1.public_ip}} groupname="CassandraLoadgen"
      with_subelements:
        - ec2_load.results
        - instances
