---
- name: Provision Scylla cluster nodes on EC2
  hosts: localhost
  connection: local
  vars:
    user_data: "--clustername {{cluster_name}} --totalnodes {{cluster_nodes}} --version={{db_version}} --release={{cassandra_ver}}"

  tasks:

    # - set_fact: image={{db_ami}}
    #   when: use_db_ami

    # - set_fact: image={{ubuntu_image}}
    #   when: use_db_ami == "false"

    # - debug: msg="using ami {{image}}"
    # - debug: msg="user_data {{user_data}}"

    # - debug: msg="{{regions}}"
    # - debug: msg="{{first_regions}}"
    # - debug: msg="{{use_regions}}"

    # - debug: msg="{{item.key}}"
    #   with_dict: regions

    # - debug: msg="{{item.key}}"
    #   with_dict: first_regions
  
    # - debug: msg="{{item.key}}"
    #   with_dict: use_regions


    - name: Launch DB server instances
      local_action:
        module: ec2
        region: "{{item.key}}"
        keypair: "{{item.value.key_name}}"
        group: "{{item.value.security_group}}"
        instance_type: "{{instance_type}}"
        # TBD add Scylla
        image: "{{item.value.cassandra_ami}}"
        count: "{{cluster_nodes}}"
        user_data: "{{user_data}}"
        volumes:
        - device_name: /dev/sdb
          ephemeral: ephemeral0
        - device_name: /dev/sdc
          ephemeral: ephemeral1
        wait: yes
      register: ec2_cluster
      with_dict: use_regions

    - name: Add instances to host group
      local_action: add_host name={{item.1.public_ip}} groupname=NewDB
      with_subelements:
        - ec2_cluster.results
        - instances

    - name: Add instances to private ip group
      local_action: add_host name={{item.1.private_ip}} groupname=DBPrivate
      when: not ec2_multiregion|bool
      with_subelements:
        - ec2_cluster.results
        - instances

    - name: Add instance 0 to seeds group
      local_action: add_host name={{ec2_cluster.results[0].instances[0].id}} groupname=Seeds
      when: not ec2_multiregion|bool

      # use prive ip as seed in one region
    - name: Add instance 0 private ip as seed
      local_action: add_host name={{groups.DBPrivate[0]}} groupname=SeedsIp
      when: not ec2_multiregion|bool

      # use public ip as seed in multi region
    - name: Add instance 0 public ip as seed
      local_action: add_host name={{groups.NewDB[0]}} groupname=SeedsIp
      when: ec2_multiregion|bool 

    - name: Tag instances
      local_action: ec2_tag resource={{item.1.id}} region={{item.1.region}} state=present
      with_subelements:
        - ec2_cluster.results
        - instances
      args:
        tags:
          Name: "DB"
          server: "{{db}}"
          stopped: "{{stopped}}"
          user: "{{setup_name}}"

    - name: Tag Seed instances
      local_action: ec2_tag resource={{item}} region={{ec2_cluster.results[0].instances[0].region}} state=present
      with_items: groups.Seeds
      args:
        tags:
          seed: "true"
      when: not ec2_multiregion|bool

    - name: Give everyone a minute or two
      pause: seconds=120
