---
- name: Provision Scylla cluster nodes on EC2
  hosts: localhost
  connection: local
  vars:
    user_data: "--clustername {{cluster_name}} --totalnodes {{cluster_nodes}} --version={{db_version}} --release={{cassandra_ver}}"

  tasks:
    - set_fact: db_ami_name="cassandra_ami"
      when: db == 'cassandra'

    - set_fact: db_ami_name="scylla_ami"
      when: db == 'scylla'

    - set_fact: ami_name="{{db_ami_name}}"
      when: use_db_ami | bool

    - set_fact: ami_name="ubuntu_image"
      when: not use_db_ami | bool

    - set_fact: image={{db_ami_name}}
      when: use_db_ami

    - set_fact: image={{ubuntu_image}}
      when: use_db_ami == "false"

    - debug: msg="using {{image}}"

    - name: Launch DB server instances
      local_action:
        module: ec2
        region: "{{item.value.region_name}}"
        keypair: "{{setup_name}}-test-and-deploy-key"
        group: "{{item.value.security_group}}"
        vpc_subnet_id: "{{item.value.vpc_subnet_id}}"
        assign_public_ip: yes
        instance_type: "{{instance_type}}"
        image: "{{item.value[image]}}"
        count: "{{cluster_nodes}}"
        user_data: "{{user_data}}"
        instance_tags:
          Name: "DB"
          server: "{{db}}"
          stopped: "{{stopped}}"
          user: "{{setup_name}}"
        wait: yes
      register: ec2_cluster
      with_dict: use_regions

    - name: Wait for SSH to come up
      wait_for: host={{item.1.public_ip}} port=22 delay=60 timeout=600 state=started
      with_subelements:
        - ec2_cluster.results
        - instances

    - name: Add instances to host group
      local_action: add_host name={{item.1.public_ip}} groupname=NewDB
      with_subelements:
        - ec2_cluster.results
        - instances

    - name: Add instances to private ip group
      local_action: add_host name={{item.1.private_ip}} groupname=DBPrivate
      when: not ec2_multiregion|bool
      with_subelements:
        - ec2_cluster.results
        - instances

    - name: Add instance 0 to seeds group
      local_action: add_host name={{ec2_cluster.results[0].instances[0].id}} groupname=Seeds
      when: not ec2_multiregion|bool

      # use prive ip as seed in one region
    - name: Add instance 0 private ip as seed
      local_action: add_host name={{groups.DBPrivate[0]}} groupname=SeedsIp
      when: not ec2_multiregion|bool

      # use public ip as seed in multi region
    - name: Add instance 0 public ip as seed
      local_action: add_host name={{groups.NewDB[0]}} groupname=SeedsIp
      when: ec2_multiregion|bool 

    - name: Tag Seed instances
      local_action: ec2_tag resource={{item}} region={{ec2_cluster.results[0].instances[0].region}} state=present
      with_items: groups.Seeds
      args:
        tags:
          seed: "true"
      when: not (ec2_multiregion|bool or add_node|bool)
