---
- name: Provision Scylla cluster nodes on EC2
  hosts: localhost
  connection: local
  vars:
    user_data: "--clustername {{cluster_name}} --totalnodes {{cluster_nodes}} --version={{db_version}} --release={{cassandra_ver}}"

  tasks:
    - set_fact: image={{db_ami}}
      when: use_db_ami

    - set_fact: image={{ubuntu_image}}
      when: use_db_ami == "false"

    - debug: msg="using ami {{image}}"
    - debug: msg="user_data {{user_data}}"

    - name: Launch {{db}} instances
      local_action:
        module: ec2
        region: "{{region}}"
        zone: "{{zone}}"
        keypair: "{{key_name}}"
        group: "{{security_group}}"
        instance_type: "{{instance_type}}"
        image: "{{image}}"
        count: "{{cluster_nodes}}"
        user_data: "{{user_data}}"
        volumes:
        - device_name: /dev/sdb
          ephemeral: ephemeral0
        - device_name: /dev/sdc
          ephemeral: ephemeral1
        wait: yes
      register: ec2_cluster

    - name: Add instances to host group
      local_action: add_host name={{item.public_ip}} groupname=NewDB
      with_items: ec2_cluster.instances

    - name: Add instances to private ip group
      local_action: add_host name={{item.private_ip}} groupname=DBPrivate
      with_items: ec2_cluster.instances
      when: not use_reflector

    - name: Add instance 0 to seeds group
      local_action: add_host name={{ec2_cluster.instances[0].id}} groupname=Seeds
      when: not use_reflector

    - name: Add instance 0 to seedsip group
      local_action: add_host name={{groups.DBPrivate[0]}} groupname=SeedsIp
      when: not use_reflector

    - name: Add instance 1 to seeds group
      local_action: add_host name={{ec2_cluster.instances[1].id}} groupname=Seeds
      when: not use_reflector and ec2_cluster.instances | length > 1

    - name: Add instance 1 to seedsip group
      local_action: add_host name={{groups.DBPrivate[1]}} groupname=SeedsIp
      when: not use_reflector and ec2_cluster.instances | length > 1

    - name: Tag instances
      local_action: ec2_tag resource={{item.id}} region={{region}} state=present
      with_items: ec2_cluster.instances
      args:
        tags:
          Name: "DB"
          server: "{{db}}"
          stopped: "{{stopped}}"
          user: "{{setup_name}}"

    - name: Tag Seed instances
      local_action: ec2_tag resource={{item}} region={{region}} state=present
      with_items: groups.Seeds
      args:
        tags:
          seed: "true"
      when: not use_reflector


    - name: Give everyone a minute or two
      pause: seconds=120
