---
- name: Provision Scylla cluster nodes on EC2
  hosts: localhost
  connection: local
  vars:
    - cluster_name: ScyllaCluster

  tasks:
    - set_fact: image={{scylla_ami}}
      when: cluster_ami

    - set_fact: image={{ubuntu_image}}
      when: cluster_ami == "false"

    - debug: msg="using ami {{image}}"

    - name: Launch instances
      local_action:
        module: ec2
        region: "{{region}}"
        zone: "{{zone}}"
        keypair: "{{key_name}}"
        group: "{{security_group}}"
        instance_type: "{{instance_type}}"
        image: "{{image}}"
        count: "{{cluster_nodes}}"
        user_data: "--clustername {{cluster_name}} --totalnodes {{cluster_nodes}}"
        volumes:
        - device_name: /dev/sdb
          ephemeral: ephemeral0
        - device_name: /dev/sdc
          ephemeral: ephemeral1
        wait: yes
      register: ec2_cluster

    - name: Add instances to host group
      local_action: add_host name={{item.public_ip}} groupname=NewDB
      with_items: ec2_cluster.instances

    - name: Tag instances
      local_action: ec2_tag resource={{item.id}} region={{region}} state=present
      with_items: ec2_cluster.instances
      args:
        tags:
          Name: "DB"
          server: "scylla"
          stopped: "{{stopped}}"
          user: "{{setup_name}}"

    - name: Give everyone a minute or two
      pause: seconds=120
