---
- name: Download stress profile from git
  hosts: localhost
  connection: local

  tasks:
    - name: git clone profile_git
      git: repo={{profile_git}} dest={{profile_dir}}
      when: profile_git is defined

- name: upload stress file to loaders
  hosts: "CassandraLoadgen"
  user: "{{loader_login}}"
  tasks:
    - name: Creates directory
      file: path="~/{{profile_file | dirname }}" state=directory
      when: profile_file is defined
    - name: upload file
      copy: src="{{profile_dir}}/{{profile_file}}" dest=~/{{profile_file}}
      when: profile_file is defined
