---
- name: Find Cassandra instance(s)
  hosts: DB
  gather_facts: false
  tasks:
    - name: Create group
      group_by: key=db_nodes

- hosts: db_nodes
  connection: local
  gather_facts: false
  tasks:
    - name: Terminate instance(s)
      ec2:
       instance_ids: "{{ ec2_id }}"
       region: "{{ ec2_region }}"
       state: absent

- name: Find CassandraLoadgen instance(s)
  hosts: CassandraLoadgen
  gather_facts: false
  tasks:
    - name: Create group
      group_by: key=loadgen_nodes

- hosts: loadgen_nodes
  connection: local
  gather_facts: false
  tasks:
    - name: Terminate instance(s)
      ec2:
        instance_ids: "{{ ec2_id }}"
        region: "{{ ec2_region }}"
        state: absent
