---
# EC2 specific vars
regions:
  us-west-2:
    cassandra_ami: ami-1cff962c # DataStax Auto-Clustering AMI 2.5.1-hvm
    scylla_ami:  ami-36617657 # scylla 0.11
    loadgen_image: ami-3f68640f # ubuntu 14.04
    ubuntu_image: ami-3f68640f # ubuntu 14.04
    key_name: tzach-oregon
    security_group: cassandra-security-group
  us-east-1:
    cassandra_ami: ami-ada2b6c4 # DataStax Auto-Clustering AMI 2.5.1-hvm
    scylla_ami:  ami-72196418 # scylla 0.11
    loadgen_image: ami-d05e75b8 # ubuntu 14.04
    ubuntu_image: ami-d05e75b8 # ubuntu 14.04
    key_name: tzach-virginia
    security_group: cassandra-security-group

# list of only the first region
first_regions:
  us-west-2: "{{regions['us-west-2']}}"


ec2_multiregion: false

use_regions: "{%if ec2_multiregion | bool %}{{regions}}{%else%}{{first_regions}}{%endif%}" 

graphite_login: ubuntu
cassandra_login: ubuntu
scylla_login: fedora
loader_login: fedora

instance_type: c3.8xlarge



setup_name: "{{ansible_env.ANSIBLE_EC2_PREFIX}}"

# graphite Server
graphite_server_type: m3.large
graphite_image: ami-29ebb519 # ubuntu
