---

- name: Install prerequisites
  yum: name={{ item }}
  become: true
  with_items:
     - wget

- name: Download Java RPM
  become: true
  command: "wget -q -O {{oracle_java_path}} --no-check-certificate --no-cookies --header 'Cookie: oraclelicense=accept-securebackup-cookie' {{oracle_java_rpm_url}} creates={{ oracle_java_path }}"

- name: install RPM
  become: true
  action: "{{ ansible_pkg_mgr }} name={{ oracle_java_path }} state=present"

- name: set Java version as default
  alternatives:
    name="{{ item.exe }}"
    link="/usr/bin/{{ item.exe }}"
    path="{{ item.path }}/{{ item.exe }}"
  with_items:
    - { path: "{{ oracle_java_home }}/jre/bin", exe: 'java' }
    - { path: "{{ oracle_java_home }}/jre/bin", exe: 'keytool' }
    - { path: "{{ oracle_java_home }}/bin", exe: 'javac' }
    - { path: "{{ oracle_java_home }}/bin", exe: 'javadoc' }
  become: true