---
- apt: pkg={{ item }} state=present update_cache=yes
  with_items:
    - docker.io
    - python-pip

- pip: name=docker-py version=0.3.2

- name: wait for Graphite server to bind 8080 port
  wait_for: port=8080

- debug: msg="Using Graphite IP {{graphite_listen_ip}}"

- name: start tessera
  shell: sudo docker run -p 80:80 -e GRAPHITE_URL=http://{{graphite_listen_ip}}:8080 -d {{docker_image}}

