---
- name: Gather facts
  action: ec2_facts

- set_fact: id="{{ansible_ec2_instance_id}}"
  when: ansible_ec2_instance_id is defined

- set_fact: index="{{ansible_ec2_ami_launch_index}}"
  when: ansible_ec2_ami_launch_index is defined

- name: Tag instance as Stopped
  local_action: ec2_tag resource={{id}} state=present region={{region}}
  when: ansible_ec2_ami_launch_index is defined
  args:
    tags:
      index: "{{index}}"
