---

- debug: msg="installing scylla packages rel {{scylla_tools_version}}"

- name: Install prerequisites
  yum: name={{ item }}
  become: true
  with_items:
     - wget
     - epel-release

- name: update repo
  get_url: url=http://downloads.scylladb.com/rpm/centos/scylla-{{scylla_tools_version}}.repo dest=/etc/yum.repos.d/scylla.repo owner=root group=root
  become: true

- name: Install Scylla
  yum: name=scylla-tools
  become: true

