---
- apt: pkg={{ item }} state=present update_cache=yes
  with_items:
    - docker.io
    - python-pip

- pip: name=docker-py version=0.3.2

- name: start graphite
  shell: sudo docker run -p 8080:80 -p 2003:2003 -p 2004:2004 -p 7002:7002 -d {{docker_image}}
