---
- service: name=cassandra enabled=yes pattern=cassandra state=stopped
- debug: msg="clean {{data_dir}}"
- file: path={{data_dir}}/data state=absent
- file: path={{data_dir}}/commitlog state=absent
- file: path={{data_dir}}/saved_caches state=absent


