---
- name: Gather facts
  action: ec2_facts

- apt: name={{ item }} state=present update_cache=yes cache_valid_time=600
  with_items:
    - collectd

- name: add libjvm.so to lib path
  lineinfile: dest=/etc/default/collectd line="export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:{{java_home}}/jre/lib/amd64/server/"

- action: template src=collectd-client.conf dest=/etc/collectd/collectd.conf owner=root group=root
  notify:
    - restart collectd
