- name: Gather facts
  action: ec2_facts

- name: install collectd client
  yum: name=collectd state=latest

- name: install collectd-netlink plugin
  yum: name=collectd-netlink state=latest

- action: template src=collectd-client.conf dest=/etc/collectd.conf owner=root group=root
  notify:
    - restart collectd
